# Generated by Django 6.0.4 on 2026-04-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
